// ============================================================================
// WEAPONS DATABASE (IMMAGINI DIRETTE IN PUBLIC/)
// ============================================================================

export const WEAPONS_DATABASE = Object.freeze([
  // ==========================================================================
  // GRADO COMUNE (#10b981)
  // ==========================================================================
  {
    id: 'wp_gatling',
    name: 'Gatling Cinetica',
    rarity: 'Comune',
    rarityColor: '#10b981',
    suit: 'spades',
    suitSymbol: '♠',
    category: 'POKER RAPIDO',
    type: 'poker',
    slotType: 'poker',
    slotAllowed: [0, 1],
    color: '#10b981',
    icon: '⚙️',
    allowedPatterns: ['one_pair', 'two_pair'],
    reqDescription: 'COPPIA',
    fxType: 'gatling',
    maxCapacity: 12,
    maxSalvo: 6,
    baseDamage: 2,
    maxShots: 3,
    cooldownDuration: 1,
    levels: {
      1: { damage: 2, shots: 4, image: '/gatling_cinetica_lv1.png', desc: 'Raffica rapida da 4 dardi traccianti' },
      2: { damage: 3, shots: 8, image: '/gatling_cinetica_lv2.png', desc: 'Raffica potenziata da 8 dardi' },
      3: { damage: 5, shots: 12, image: '/gatling_cinetica_lv3.png', desc: 'Scarica a nastro da 12 dardi cinetici' }
    }
  },
  {
    id: 'wp_fuse_bolts',
    name: 'Balestra Dardi Fusi',
    rarity: 'Comune',
    rarityColor: '#10b981',
    suit: 'diamonds',
    suitSymbol: '♦',
    category: 'POKER RAPIDO',
    type: 'poker',
    slotType: 'poker',
    slotAllowed: [0, 1],
    color: '#10b981',
    icon: '🏹',
    allowedPatterns: ['one_pair'],
    reqDescription: 'COPPIA',
    fxType: 'fuse_bolts',
    maxCapacity: 10,
    maxSalvo: 4,
    baseDamage: 3,
    maxShots: 2,
    cooldownDuration: 1,
    levels: {
      1: { damage: 3, shots: 2, image: '/balestra_dardi_fusi_lv1.png', desc: '2 arpioni fusi incandescenti' },
      2: { damage: 4, shots: 3, image: '/balestra_dardi_fusi_lv2.png', desc: '3 arpioni a ventaglio termico' },
      3: { damage: 6, shots: 4, image: '/balestra_dardi_fusi_lv3.png', desc: '4 arpioni pesanti perforanti' }
    }
  },
  {
    id: 'wp_disc_blades',
    name: 'Lame Rotanti',
    rarity: 'Comune',
    rarityColor: '#10b981',
    suit: 'spades',
    suitSymbol: '♠',
    category: 'POKER RAPIDO',
    type: 'poker',
    slotType: 'poker',
    slotAllowed: [0, 1],
    color: '#10b981',
    icon: '🥏',
    allowedPatterns: ['two_pair'],
    reqDescription: 'DOPPIA COPPIA',
    fxType: 'disc_blades',
    maxCapacity: 12,
    maxSalvo: 4,
    baseDamage: 3,
    maxShots: 3,
    cooldownDuration: 1,
    levels: {
      1: { damage: 3, shots: 2, image: '/lame_rotanti_lv1.png', desc: '2 carte rotanti a disco' },
      2: { damage: 4, shots: 4, image: '/lame_rotanti_lv2.png', desc: '4 dischi di luce tagliente' },
      3: { damage: 6, shots: 6, image: '/lame_rotanti_lv3.png', desc: '6 dischi con taglio orizzontale' }
    }
  },
  {
    id: 'wp_thunderstrike',
    name: 'Fulmine a Ciel Sereno',
    rarity: 'Comune',
    rarityColor: '#10b981',
    suit: 'diamonds',
    suitSymbol: '♦',
    category: 'CALCOLO TATTICO',
    type: 'math',
    slotType: 'math',
    slotAllowed: [2, 3],
    mathOp: '+',
    target: 14,
    color: '#10b981',
    icon: '⚡',
    reqDescription: 'SOMMA [+]',
    fxType: 'lightning_strike',
    maxCapacity: 14,
    maxSalvo: 4,
    baseDamage: 3,
    maxShots: 3,
    cooldownDuration: 1,
    levels: {
      1: { damage: 3, bolts: 1, image: '/fulmine_ciel_sereno_lv1.png', desc: '1 fulmine secco verticale' },
      2: { damage: 4, bolts: 2, image: '/fulmine_ciel_sereno_lv2.png', desc: '2 fulmini ramificati simultanei' },
      3: { damage: 6, bolts: 3, image: '/fulmine_ciel_sereno_lv3.png', desc: '3 fulmini con scarica continua' }
    }
  },
  {
    id: 'wp_railgun',
    name: 'Railgun Ionico',
    rarity: 'Comune',
    rarityColor: '#10b981',
    suit: 'spades',
    suitSymbol: '♠',
    category: 'CALCOLO TATTICO',
    type: 'math',
    slotType: 'math',
    slotAllowed: [2, 3],
    mathOp: '-',
    target: 4,
    color: '#10b981',
    icon: '🎯',
    reqDescription: 'DIFFERENZA [-]',
    fxType: 'railgun_beam',
    maxCapacity: 10,
    maxSalvo: 2,
    baseDamage: 6,
    maxShots: 2,
    cooldownDuration: 1,
    levels: {
      1: { damage: 6, image: '/railgun_ionico_lv1.png', desc: 'Fascio istantaneo che taglia la barra' },
      2: { damage: 9, image: '/railgun_ionico_lv2.png', desc: 'Raggio potenziato con anelli magnetici' },
      3: { damage: 13, image: '/railgun_ionico_lv3.png', desc: 'Fascio ultra-denso con scintille ioniche' }
    }
  },
  {
    id: 'wp_seismic_wave',
    name: 'Lama Sismica',
    rarity: 'Comune',
    rarityColor: '#10b981',
    suit: 'clubs',
    suitSymbol: '♣',
    category: 'CALCOLO TATTICO',
    type: 'math',
    slotType: 'math',
    slotAllowed: [2, 3],
    mathOp: '-',
    isTriple: true,
    target: 5,
    color: '#10b981',
    icon: '🌊',
    reqDescription: 'DIFFERENZA 3 CARTE [-]',
    fxType: 'seismic_wave',
    maxCapacity: 12,
    maxSalvo: 3,
    baseDamage: 5,
    maxShots: 2,
    cooldownDuration: 1,
    levels: {
      1: { damage: 5, image: '/lama_sismica_lv1.png', desc: 'Mezzaluna di luce che sale dal basso' },
      2: { damage: 8, image: '/lama_sismica_lv2.png', desc: 'Doppia onda sismica concentrica' },
      3: { damage: 12, image: '/lama_sismica_lv3.png', desc: 'Lama densa con distorsione sismica' }
    }
  },

  // ==========================================================================
  // GRADO RARA (#38bdf8)
  // ==========================================================================
  {
    id: 'wp_xbow',
    name: 'Arco-X Balistico',
    rarity: 'Rara',
    rarityColor: '#38bdf8',
    suit: 'clubs',
    suitSymbol: '♣',
    category: 'POKER AVANZATO',
    type: 'poker',
    slotType: 'poker',
    slotAllowed: [0, 1],
    color: '#38bdf8',
    icon: '🌠',
    allowedPatterns: ['three_of_a_kind', 'straight', 'flush'],
    reqDescription: 'TRIS / SCALA',
    fxType: 'arrow_barrage',
    maxCapacity: 12,
    maxSalvo: 4,
    baseDamage: 4,
    maxShots: 2,
    cooldownDuration: 2,
    levels: {
      1: { damage: 4, shots: 8, image: '/arco_x_balistico_lv1.png', desc: 'Pioggia continua di 8 frecce balistiche' },
      2: { damage: 6, shots: 12, image: '/arco_x_balistico_lv2.png', desc: 'Pioggia rapida di 12 frecce balistiche' },
      3: { damage: 9, shots: 16, image: '/arco_x_balistico_lv3.png', desc: 'Tempesta di 16 frecce al plasma ciano' }
    }
  },
  {
    id: 'wp_siege_cannon',
    name: 'Cannone d\'Assedio',
    rarity: 'Rara',
    rarityColor: '#38bdf8',
    suit: 'hearts',
    suitSymbol: '♥',
    category: 'POKER AVANZATO',
    type: 'poker',
    slotType: 'poker',
    slotAllowed: [0, 1],
    color: '#38bdf8',
    icon: '💣',
    allowedPatterns: ['three_of_a_kind'],
    reqDescription: 'TRIS',
    fxType: 'heavy_cannon',
    maxCapacity: 8,
    maxSalvo: 1,
    baseDamage: 18,
    maxShots: 1,
    cooldownDuration: 2,
    levels: {
      1: { damage: 18, shots: 1, image: '/cannone_assedio_lv1.png', desc: 'Colpo pesante ad alta inerzia dal basso' },
      2: { damage: 26, shots: 1, image: '/cannone_assedio_lv2.png', desc: 'Colpo sferico con onda d\'urto conica' },
      3: { damage: 38, shots: 1, image: '/cannone_assedio_lv3.png', desc: 'Colpo incendiario con scuotimento' }
    }
  },
  {
    id: 'wp_blood_siphon',
    name: 'Sifone di Sangue',
    rarity: 'Rara',
    rarityColor: '#38bdf8',
    suit: 'hearts',
    suitSymbol: '♥',
    category: 'POKER AVANZATO',
    type: 'poker',
    slotType: 'poker',
    slotAllowed: [0, 1],
    color: '#38bdf8',
    icon: '🩸',
    allowedPatterns: ['flush'],
    reqDescription: 'COLORE (♥)',
    fxType: 'blood_siphon',
    maxCapacity: 10,
    maxSalvo: 3,
    baseDamage: 4,
    maxShots: 2,
    cooldownDuration: 2,
    levels: {
      1: { damage: 4, heal: 8, shots: 3, image: '/sifone_sangue_lv1.png', desc: 'Dardi cremisi e cura +8 HP' },
      2: { damage: 6, heal: 14, shots: 3, image: '/sifone_sangue_lv2.png', desc: 'Dardi a scia vitale e cura +14 HP' },
      3: { damage: 9, heal: 22, shots: 4, image: '/sifone_sangue_lv3.png', desc: 'Assorbimento denso e cura +22 HP' }
    }
  },
  {
    id: 'wp_orbital_cannon',
    name: 'Raggio Orbitale',
    rarity: 'Rara',
    rarityColor: '#38bdf8',
    suit: 'clubs',
    suitSymbol: '♣',
    category: 'CALCOLO PESANTE',
    type: 'math',
    slotType: 'math',
    slotAllowed: [2, 3],
    mathOp: '*',
    target: 24,
    color: '#38bdf8',
    icon: '🌌',
    reqDescription: 'MOLTIPLICA [*]',
    fxType: 'orbital_pillar',
    maxCapacity: 10,
    maxSalvo: 2,
    baseDamage: 8,
    maxShots: 2,
    cooldownDuration: 2,
    levels: {
      1: { damage: 8, bolts: 1, image: '/raggio_orbitale_lv1.png', desc: 'Colonna di luce continua dal cielo' },
      2: { damage: 12, bolts: 1, image: '/raggio_orbitale_lv2.png', desc: 'Colonna larga con scansione orizzontale' },
      3: { damage: 18, bolts: 2, image: '/raggio_orbitale_lv3.png', desc: 'Fascio ionico orbitale denso' }
    }
  },
  {
    id: 'wp_tesla_arc',
    name: 'Torre Tesla',
    rarity: 'Rara',
    rarityColor: '#38bdf8',
    suit: 'diamonds',
    suitSymbol: '♦',
    category: 'CALCOLO TATTICO',
    type: 'math',
    slotType: 'math',
    slotAllowed: [2, 3],
    mathOp: '+',
    requireEven: true,
    target: 14,
    color: '#38bdf8',
    icon: '⚡',
    reqDescription: 'SOMMA PARI [+]',
    fxType: 'tesla_arc',
    maxCapacity: 12,
    maxSalvo: 3,
    baseDamage: 5,
    maxShots: 2,
    cooldownDuration: 1,
    levels: {
      1: { damage: 5, image: '/torre_tesla_lv1.png', desc: 'Scariche ramificate che friggono la barra' },
      2: { damage: 8, image: '/torre_tesla_lv2.png', desc: 'Arco voltaico continuo ad alta frequenza' },
      3: { damage: 12, image: '/torre_tesla_lv3.png', desc: 'Tempesta di scariche orizzontali' }
    }
  },
  {
    id: 'wp_cross_laser',
    name: 'Taglio Frazionato',
    rarity: 'Rara',
    rarityColor: '#38bdf8',
    suit: 'hearts',
    suitSymbol: '♥',
    category: 'CALCOLO TATTICO',
    type: 'math',
    slotType: 'math',
    slotAllowed: [2, 3],
    mathOp: '/',
    target: 2,
    color: '#38bdf8',
    icon: '🔥',
    reqDescription: 'DIVISIONE [/]',
    fxType: 'cross_laser',
    maxCapacity: 8,
    maxSalvo: 2,
    baseDamage: 7,
    maxShots: 2,
    cooldownDuration: 1,
    levels: {
      1: { damage: 7, image: '/taglio_frazionato_lv1.png', desc: '2 lame laser dagli angoli inferiori a X' },
      2: { damage: 11, image: '/taglio_frazionato_lv2.png', desc: 'Taglio a X con riverbero energetico' },
      3: { damage: 16, image: '/taglio_frazionato_lv3.png', desc: 'Triplo taglio geometrico sincronizzato' }
    }
  },

  // ==========================================================================
  // GRADO EPICA (#c084fc)
  // ==========================================================================
  {
    id: 'wp_flak_cannon',
    name: 'Flak a Grappolo',
    rarity: 'Epica',
    rarityColor: '#c084fc',
    suit: 'clubs',
    suitSymbol: '♣',
    category: 'POKER AVANZATO',
    type: 'poker',
    slotType: 'poker',
    slotAllowed: [0, 1],
    color: '#c084fc',
    icon: '💥',
    allowedPatterns: ['full_house'],
    reqDescription: 'FULL',
    fxType: 'flak_burst',
    maxCapacity: 12,
    maxSalvo: 4,
    baseDamage: 6,
    maxShots: 2,
    cooldownDuration: 1,
    levels: {
      1: { damage: 6, shots: 6, image: '/flak_grappolo_lv1.png', desc: 'Testata che si apre in 6 ogive' },
      2: { damage: 9, shots: 8, image: '/flak_grappolo_lv2.png', desc: 'Frammentazione in 8 ogive a ventaglio' },
      3: { damage: 13, shots: 10, image: '/flak_grappolo_lv3.png', desc: 'Frammentazione a 10 ogive con scintille' }
    }
  },
  {
    id: 'wp_kinetic_drill',
    name: 'Trivella a Torsione',
    rarity: 'Epica',
    rarityColor: '#c084fc',
    suit: 'spades',
    suitSymbol: '♠',
    category: 'POKER AVANZATO',
    type: 'poker',
    slotType: 'poker',
    slotAllowed: [0, 1],
    color: '#c084fc',
    icon: '🔩',
    allowedPatterns: ['straight'],
    reqDescription: 'SCALA (5 CARTE)',
    fxType: 'kinetic_drill',
    maxCapacity: 14,
    maxSalvo: 5,
    baseDamage: 5,
    maxShots: 2,
    cooldownDuration: 2,
    levels: {
      1: { damage: 5, ticks: 4, image: '/trivella_torsione_lv1.png', desc: 'Fuso conico che trapana la barra per 1s' },
      2: { damage: 7, ticks: 6, image: '/trivella_torsione_lv2.png', desc: 'Trivella ad alta velocità con vortice' },
      3: { damage: 11, ticks: 8, image: '/trivella_torsione_lv3.png', desc: 'Perforatore rotante al plasma continuo' }
    }
  },
  {
    id: 'wp_meteor_strike',
    name: 'Meteora a 45°',
    rarity: 'Epica',
    rarityColor: '#c084fc',
    suit: 'hearts',
    suitSymbol: '♥',
    category: 'CALCOLO PESANTE',
    type: 'math',
    slotType: 'math',
    slotAllowed: [2, 3],
    mathOp: '+',
    isTriple: true,
    target: 21,
    color: '#c084fc',
    icon: '☄️',
    reqDescription: 'SOMMA 3 CARTE [+]',
    fxType: 'meteor_drop',
    maxCapacity: 10,
    maxSalvo: 2,
    baseDamage: 11,
    maxShots: 1,
    cooldownDuration: 2,
    levels: {
      1: { damage: 11, image: '/meteora_45_lv1.png', desc: 'Masso infuocato dall\'alto con fumo' },
      2: { damage: 16, image: '/meteora_45_lv2.png', desc: 'Meteora pesante con onda d\'urto' },
      3: { damage: 23, image: '/meteora_45_lv3.png', desc: 'Asteroide vulcanico con schegge' }
    }
  },
  {
    id: 'wp_cryo_fracture',
    name: 'Frattura Criogenica',
    rarity: 'Epica',
    rarityColor: '#c084fc',
    suit: 'clubs',
    suitSymbol: '♣',
    category: 'CALCOLO PESANTE',
    type: 'math',
    slotType: 'math',
    slotAllowed: [2, 3],
    mathOp: '/',
    target: 2,
    color: '#c084fc',
    icon: '❄️',
    reqDescription: 'DIVISIONE [/]',
    fxType: 'cryo_fracture',
    maxCapacity: 8,
    maxSalvo: 2,
    baseDamage: 12,
    maxShots: 2,
    cooldownDuration: 2,
    levels: {
      1: { damage: 12, image: '/frattura_criogenica_lv1.png', desc: 'La barra nemica si congela e si frantuma' },
      2: { damage: 17, image: '/frattura_criogenica_lv2.png', desc: 'Gelo profondo con stalattiti di ghiaccio' },
      3: { damage: 24, image: '/frattura_criogenica_lv3.png', desc: 'Frattura criogenica a schegge vitree' }
    }
  },

  // ==========================================================================
  // GRADO LEGGENDARIA (#facc15)
  // ==========================================================================
  {
    id: 'wp_micro_missiles',
    name: 'Sciame Microrazzi',
    rarity: 'Leggendaria',
    rarityColor: '#facc15',
    suit: 'diamonds',
    suitSymbol: '♦',
    category: 'POKER AVANZATO',
    type: 'poker',
    slotType: 'poker',
    slotAllowed: [0, 1],
    color: '#facc15',
    icon: '🚀',
    allowedPatterns: ['four_of_a_kind'],
    reqDescription: 'POKER',
    fxType: 'micro_missiles',
    maxCapacity: 16,
    maxSalvo: 6,
    baseDamage: 5,
    maxShots: 1,
    cooldownDuration: 2,
    levels: {
      1: { damage: 5, shots: 4, image: '/sciame_microrazzi_lv1.png', desc: '4 missili a traiettoria curva' },
      2: { damage: 8, shots: 6, image: '/sciame_microrazzi_lv2.png', desc: '6 missili con convergenza a sciame' },
      3: { damage: 12, shots: 8, image: '/sciame_microrazzi_lv3.png', desc: '8 missili guidati con scia densa' }
    }
  },
  {
    id: 'wp_apocalypse_torpedo',
    name: 'Siluro Apocalisse',
    rarity: 'Leggendaria',
    rarityColor: '#facc15',
    suit: 'hearts',
    suitSymbol: '♥',
    category: 'POKER AVANZATO',
    type: 'poker',
    slotType: 'poker',
    slotAllowed: [0, 1],
    color: '#facc15',
    icon: '🌠',
    allowedPatterns: ['royal_flush'],
    reqDescription: 'SCALA REALE',
    fxType: 'apocalypse_torpedo',
    maxCapacity: 8,
    maxSalvo: 1,
    baseDamage: 38,
    maxShots: 1,
    cooldownDuration: 3,
    levels: {
      1: { damage: 38, shots: 1, image: '/siluro_apocalisse_lv1.png', desc: 'Testata colossale e flash bianco sullo schermo' },
      2: { damage: 56, shots: 1, image: '/siluro_apocalisse_lv2.png', desc: 'Detonazione nucleare a onde d\'urto' },
      3: { damage: 80, shots: 1, image: '/siluro_apocalisse_lv3.png', desc: 'Esplosione accecante con terremoto totale' }
    }
  },
  {
    id: 'wp_singularity_blackhole',
    name: 'Micro Buco Nero',
    rarity: 'Leggendaria',
    rarityColor: '#facc15',
    suit: 'spades',
    suitSymbol: '♠',
    category: 'CALCOLO PESANTE',
    type: 'math',
    slotType: 'math',
    slotAllowed: [2, 3],
    mathOp: '*',
    isTriple: true,
    target: 30,
    color: '#facc15',
    icon: '🕳️',
    reqDescription: 'MOLTIPLICA [*]',
    fxType: 'black_hole',
    maxCapacity: 10,
    maxSalvo: 1,
    baseDamage: 30,
    maxShots: 1,
    cooldownDuration: 3,
    levels: {
      1: { damage: 30, image: '/micro_buco_nero_lv1.png', desc: 'Sfera gravitazionale che risucchia gli HP' },
      2: { damage: 45, image: '/micro_buco_nero_lv2.png', desc: 'Singolarità con disco di accrescimento rotante' },
      3: { damage: 65, image: '/micro_buco_nero_lv3.png', desc: 'Buco nero ultra-denso con distorsione' }
    }
  },
  {
    id: 'wp_reactor_bomb',
    name: 'Nucleo Instabile (Bomba)',
    rarity: 'Leggendaria',
    rarityColor: '#facc15',
    suit: 'diamonds',
    suitSymbol: '♦',
    category: 'ALLERTA BOMBA',
    type: 'math',
    slotType: 'math',
    slotAllowed: [2, 3],
    mathOp: '*',
    target: 36,
    isBomb: true,
    color: '#facc15',
    icon: '⚛️',
    reqDescription: 'DISINNESCO 3T',
    fxType: 'reactor_bomb',
    maxCapacity: 15,
    maxSalvo: 3,
    baseDamage: 14,
    maxShots: 1,
    cooldownDuration: 3,
    levels: {
      1: { damage: 14, turns: 3, image: '/nucleo_instabile_lv1.png', desc: 'Testata a reattore che detona sulla barra' },
      2: { damage: 20, turns: 3, image: '/nucleo_instabile_lv2.png', desc: 'Bomba termonucleare con fungo al plasma' },
      3: { damage: 30, turns: 3, image: '/nucleo_instabile_lv3.png', desc: 'Detonazione a reazione di fusione' }
    }
  }
]);